const Somethings = [
    "something",
    "peace",
    "lies",
    "some lies",
    "some peace",
    "peacefully",
    "jokes",
    "secrets",
    "confessions",
    "updates",
    "laughs",
    "memes",
    "dox",
    "dark secrets",
    "dark confessions",
    "anonymously",
    "like an idiot",
    "like a boss",
    "like a bawss",
    "as humans do",
    "as a human would",
    "without having to log in",
    "something that only the REAL you would know",
    "something that only the REAL you would say",
    "a status update",
    "a secret",
    "a confession",
    "a dark truth",
    "an acknowledgement",
    "an admission",
    "a dark admission",
    "a concession",
    "a dark concession",
    "a disclosure",
    "a protestation",
    "a lie",
    "a complete sentence",
    "a run-on sentence",
    "without thinking",
    "a non sequitur",
    "something random",
    "or whatever",
    "lies, damn lies",
    "a sinister lie",
    "some truth",
    "a truth",
    "your truth",
    "a complaint",
    "a gripe",
    "a grievance",
    "an objection",
    "some trouble",
    "a remonstrance",
    "a squawk",
    "a wail",
    "a whine",
    "a whinge",
    "a joke",
    "some guff",
    "some grouse",
    "an expostulation",
    "about your favorite song",
    "a sentence or two",
    "something happy",
    "something friendly",
    "something funny",
    "something foolish",
    "something absurd",
    "something ridiculous",
    "something surreal",
    "something meaningful",
    "something meaningless",
    "something stupid",
    "something smart",
    "something brilliant",
    "something controversial",
    "something agreeable",
    "something, if you must.",
    "like no one's watching",
    "as though your life depended on it",
    "because the alternative is NOT posting",
    "something you'd never admit to posting",
    "something. Why not?",
    "something. Why wouldn't you?",
    "something. What have you got to lose?",
    "something. What else is there to do?",
    "something. Nobody will know it's you.",
    "something. Who cares?",
    "something. You must.",
    "something. Come on, everybody's doing it.",
    "something. You know you want to",
    "something you will, hmmm?",
    "something. It's the only way.",
    "something. Everything depends on it.",
    "something. Everyone is counting on you.",
    "something, please.",
    "something, human.",
    "something, Cadet. That's an order.",
    "something, Marine. That's an order.",
    "something, Soldier. That's an order.",
    "something, Sailor. That's an order.",
    "something, Ensign. That's an order.",
    "something, Crewman. That's an order.",
    "something, Lieutenant. That's an order.",
    "someone else's passwords",
    "something nobody cares about",
    "when you're in a bad mood",
    "into the void",
    "upon the eternal scrolls",
    "to the Internet!",
    "on the Internet!",
    "to the Intertubes",
    "like a leet haxor",
    "or ELSE",
    "something -- THIS MEANS YOU",
    "or don't. I can't control you.",
    "somethin' will ya!",
    "a thing",
    "things",
    "stuff",
    "don't Tweet",
    "you must, hmmm?",
    "man",
    "my dudes",
    "bruh",
    "bro",
    "without Jack censoring you",
    "sumfin",
    "sumfing",
    "somefin",
    "sumpfing",
    "sumpin",
    "stuff here",
    "here",
    "right here",
    "whatever you want",
    "whatever you think should be posted",
    "from the bottom of your heart",
    "a post",
    "freely",
    "literally anything",
    "if you want",
    "legally",
    "for your supper",
    "and then dance",
    "and then un-post",
    "something, OR ELSE",
    "forbodingly",
    "with emoticons",
    "using words",
    "words",
    "a half-baked idea",
    "to your heart's content",
    "though, okay?",
    "McPostface",
    "excellently",
    "well, friend.",
    "using this box",
    "and all the other posts will move down",
    "using markdown",
    "with markdown",
    "in markdown",
    "something (markdown supported)."
];

const getSomething = (req, res, next) => {
    var rand = Math.round(Math.random() * Somethings.length);
    console.log(rand);
    res.status(200).json({
        something: Somethings[rand]
    });
    next();
};

module.exports = {
    getSomething
};